### ISSUE TITLE
list kr dns not working adguard mobile

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#259]
<details>
<summary>Screenshot</summary>

![Screenshot_20220324-002912_AdGuard](https://user-images.githubusercontent.com/34261355/159735777-ca112afd-f483-4659-944d-2cb07752ddb1.jpg)

</details>

**Comment by piquark6046** [comment]
AdGuard for Android v3.6.7?

**Comment by piquark6046** [comment]
It seems that your issue is related to a bug of AdGuard for Android.

<details>
<summary>AdGuard for Windows 7.9.1</summary>

![Screenshot from 2022-03-23 15-38-10](https://user-images.githubusercontent.com/98787049/159738901-27e8a25b-10c0-4426-a27f-4fc28083a968.png)


</details>

Please report it at [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/new).

**Comment by green1052** [comment]
👌

**Comment by ghost** [comment]
@green1052 
Some ad blockers like Brave don't seem to support the !#include syntax.
Instead of https://github.com/List-US/List-US/raw/master/filter_DNS.txt
https://github.com/List-KR/List-KR/raw/master/filters-share/adserver.txt
https://github.com/List-KR/List-KR/raw/master/filters-share/adserver_firstparty.txt
Would you like to test it after subscribing?

**Comment by green1052** [comment]
> @green1052 Some ad blockers like Brave don't seem to support the !#include syntax. Instead of https://github.com/List-US/List-US/raw/master/filter_DNS.txt https://github.com/List-KR/List-KR/raw/master/filters-share/adserver.txt https://github.com/List-KR/List-KR/raw/master/filters-share/adserver_firstparty.txt Would you like to test it after subscribing?

![Screenshot_20220330-153538_AdGuard](https://user-images.githubusercontent.com/34261355/160766827-d479abd7-a89d-440c-a219-2434c9b7892f.jpg)
 its working
