### ISSUE TITLE
파이어폭스에서 필터 갱신이 안됩니다

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#436]
네트워크 오류로 인해 리소스가 업데이트되지 못했습니다
a network error prevented the resource from being update

매일 ublock origin 필터 업데이트때 오류가 발생합니다

LIst-KR만 업데이트가 안됩니다
엣지 브라우저는 아무런 오류가 발생하지 않습니다
파이어폭스만 안됩니다

**Comment by piquark6046** [comment]
@whatareyoudoingfor 
Your issue is a bug of uBlock Origin.
Please create new Firefox profile [^1] and use it.

Or, please add the following filters into `My filters`[^2]:
```
@@||raw.githubusercontent.com/List-KR/List-KR/master/
@@||github.com/List-KR/List-KR/raw/master/
@@||cdn.jsdelivr.net/gh/List-KR/List-KR@master/
@@||cdn.statically.io/gh/List-KR/List-KR/master/
@@||combinatronics.io/List-KR/List-KR/master/
@@||gitcdn.link/cdn/List-KR/List-KR/master/
```


[^1]: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US
[^2]: https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
