### ISSUE TITLE
Request to remove script that waits 1 minute

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#517]
URL:  https://digitoy.tistory.com/pages/Serum-134b5%EB%B2%84%EC%A0%84-%EC%9B%8C%ED%81%AC%EC%97%85%EB%A1%9C%EB%93%9C-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-%ED%8E%98%EC%9D%B4%EC%A7%80

![10](https://user-images.githubusercontent.com/99063049/192504593-7367a184-6b76-4bd1-82da-58d740fefcd0.png)

**Comment by piquark6046** [comment]
Sorry, but I cannot add a proper rule into AdGuard Annoyances filter because its visitor count is lower than 100 000 per month. [^1][^2]

You can block the script manually by adding the following rule into your user rules:
```adblock
digitoy.tistory.com#%#//scriptlet("abort-current-inline-script", "document.getElementById", "button")
```

[^1]: https://kb.adguard.com/en/general/adguard-filter-policy#limitations-and-exceptions-4
[^2]: https://www.similarweb.com/website/digitoy.tistory.com/#traffic
