### ISSUE TITLE
AD: www.clien.net

### ISSUE THREAD

**Issue by tgp0625** [List-KR/List-KR#523]
### URL

https://www.clien.net/

### FILTERS

List-KR
AdGuard Base filter

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

제 pc에서는 페이지가 로드 되면서 ad-shield-inventory에 속한 광고 영역이 제거될 때 잔상(해당 영역이 표시되었다가 제거되는 현상)이 발생합니다

많이 거슬려서 웹은 모르는 분야이지만 한 번 이를 해결하는 규칙을 만들어봤습니다

깔끔하고 보기 좋은 공통 규칙으로 간단하게 해결하는 방법을 고민해봤으나 제 능력 부족으로 어쩔 수 없이 무식하게 각 영역에 대한 규칙을 추가할 수 밖에 없네요

규칙의 적용 순서는(콤마로 구분) 
메인 페이지 - 오른쪽 상단 로그인 창 아래(사이드)
메인 페이지 -  운영 알림판
메인 페이지 - 중간
게시판 상단, 게시물 - 회원의 지난 게시글 옆
입니다
www.clien.net#$#div.aside > div#side_clien, div.section_list.notice > div[class^="main_top_"], div.contents_main > div[class^="main_center_"], div#div_content.content_list > div[class^="list_top_"], div#div_content > div.post_view > div.post_writer > div[class^="view_center_"] { display: none !important; }

**Comment by piquark6046** [comment]
> 제 pc에서는 페이지가 로드 되면서 ad-shield-inventory에 속한 광고 영역이 제거될 때 잔상(해당 영역이 표시되었다가 제거되는 현상)이 발생합니다

It is inevitable because the short time is required while extended CSS checks.
Extended CSS가 검사하는데 시간이 필요하기 때문에 불가피합니다.

> 깔끔하고 보기 좋은 공통 규칙으로 간단하게 해결하는 방법을 고민해봤으나 제 능력 부족으로 어쩔 수 없이 무식하게 각 영역에 대한 규칙을 추가할 수 밖에 없네요

Originally, I have applied using a cosmetic rule when resolving a common issue.
However, It seems that the end of `class` value is random, and blocking those elements without incorrect blocking is difficult for cosmetic rules.
원래, 전 일반적인 이슈를 해결하라고 했을 때 cosmetic 규칙을 사용해왔었습니다.
그러나, `class` 값의 끝이 랜덤으로 보이고, 오차단 없이 이러한 요소들을 차단하는 것은 cosmetic 규칙에겐 어렵습니다.
