### ISSUE TITLE
AD: medipana.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#535]
### URL

https://www.medipana.com/

### FILTERS

list-kr

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/99063049/195311000-d2ededae-eaf4-49f9-b365-215d3031eab8.png)

**Comment by piquark6046** [comment]
Unfortunately, blocking the popup cannot be default with AdGuard Annoyances filter because number of its visitor is lower than 100 K. [^1][^2]
You can block it by adding the following rules into your user rules:
```adblock
||medipana.com/upload/popup/
medipana.com##.wrap_mainPopup
```

[^1]: https://www.similarweb.com/website/medipana.com/#traffic
[^2]: https://kb.adguard.com/en/general/adguard-filter-policy#limitations-and-exceptions-4
