### ISSUE TITLE
AD: sonagitv.live

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#613]
### URL

https://s1.sonagitv.live/

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter.txt

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

**Comment by piquark6046** [comment]
Due to [Apple iOS API's restriction](https://developer.apple.com/documentation/safariservices/creating_a_content_blocker), you cannot block the advertisement via a regex rule on website.

<details><summary>한국어 - Korean</summary>

[Apple iOS의 제한](https://developer.apple.com/documentation/safariservices/creating_a_content_blocker)으로 인해 웹 사이트에 있는 광고를 정규 표현식 규칙으로 차단할 수 없습니다.

</details>
