### ISSUE TITLE
cgv.co.kr

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#702]
- https://m.cgv.co.kr

**Comment by seia-soto** [comment]
@piquark6046 Did you mean this section?

![image](https://github.com/List-KR/List-KR/assets/30369714/deaf0e1a-12bc-44ad-934f-c9910aac638c)

**Comment by piquark6046** [comment]
Actually, I created this issue to resolve a breakage issue [^1] reported from a giggle user.
But, I cannot reproduce that. If you want to handle this issue, please unassign me and assign yourself.

[^1]: The reporter said a breakage issue exists in selecting seat during purchasing a ticket.

**Comment by seia-soto** [comment]
There isn't enough information on my side too. Can you share what's actually breakage? Is that element I high lighted correct?

**Comment by piquark6046** [comment]
Edited the previous comment to add the breakage.

> Is that element I high lighted correct?

Also, please check its menu.

**Comment by seia-soto** [comment]
I reproduced on mobile but not sure yet. I'll take over.

**Comment by seia-soto** [comment]
@piquark6046 It seems like we need a Google Analytics script shim as they're using built-in API to direct pages.

Since the function `ga_cgv` is Google Analytics function but the script did not load, both `hitCallback` and `hitCallbackFail` will not be called.

Do you know related function in ad blocker to resolve this?

![image](https://github.com/List-KR/List-KR/assets/30369714/a4bd75f7-c324-45cd-b27d-53fdbb701359)

**Comment by piquark6046** [comment]
Please try `set-constant` scriptlet.
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-constant
https://github.com/gorhill/uBlock/wiki/Resources-Library#set-constantjs-

**Comment by seia-soto** [comment]
Unable to resolve: https://adguard.com/kb/general/ad-filtering/create-own-filters/#redirect-modifier
